name: Terraform + Build + Deploy (ECS Fargate)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-north-1
      TF_VAR_aws_region: eu-north-1
      TF_VAR_project: ${{ secrets.PROJECT }}
      TF_VAR_tf_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
      TF_VAR_tf_lock_table: ${{ secrets.TF_LOCK_TABLE }}
      TF_VAR_ecr_repo_name: ${{ secrets.ECR_REPO_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::621072894747:role/ECS_GitHub
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=${TF_VAR_tf_state_bucket}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_VAR_tf_lock_table}" \
            -backend-config="key=ecs-fargate-demo/terraform.tfstate"

      - name: Terraform Apply (Provision Infra)
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image (latest + sha)
        run: |
          ACCOUNT_ID=621072894747
          REPO=${TF_VAR_ecr_repo_name}
          IMAGE_LATEST=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}:latest
          IMAGE_SHA=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}:${GITHUB_SHA}

          docker build -t ecs-app .
          docker tag ecs-app:latest $IMAGE_LATEST
          docker tag ecs-app:latest $IMAGE_SHA

          docker push $IMAGE_LATEST
          docker push $IMAGE_SHA

      - name: Force ECS new deployment (auto-detect service)
        run: |
          CLUSTER=${TF_VAR_project}

          SERVICE_ARN=$(aws ecs list-services --cluster "$CLUSTER" --region "${AWS_REGION}" --query "serviceArns[0]" --output text)

          echo "Detected service ARN: $SERVICE_ARN"

          aws ecs update-service \
            --cluster "$CLUSTER" \
            --service "$SERVICE_ARN" \
            --force-new-deployment \
            --region "${AWS_REGION}"
